apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: sogoinc/test_aplication_withkubernetes:master
        imagePullPolicy: Always
        ports:
          - name: server-service
            containerPort: 8000
